name: Generate website

on:
  workflow_dispatch:
    inputs:
      art: 
        description: "Describe a piece of AI-generated art to include in the site"
        default: "The 2026 Lexus LFR driving on a mountain road."
      prompt:
        description: "Describe the type of HTML page to generate"
        required: true
        default: "Give info about the rumored Lexus LFR speculations, like engine, transmission, price, etc."
      theme: 
        description: "Describe the color scheme and theme for generating CSS"
        default: "Modern and minimalist, similar to Apple's theme"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false


env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  
jobs:
  generate-art:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl
        
      - name: Call OpenAI API to generate art
        run: |
          curl -X POST "https://api.openai.com/v1/images/generations" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-type: application/json" \
            -d '{
                "model": "gpt-image-1",
                "prompt": "${{ github.event.inputs.art }}"
            }' > response.json
            
      - name: Extract PNG image from response
        run: |
          jq -r '.data[0].b64_json' response.json | base64 --decode > image.png

      - name: Commit and push generated PNG image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add image.png
          git commit -m "Auto-generate image.png using OpenAI API" || echo "No changes to commit"
          git push
      
  generate-html:
    runs-on: ubuntu-latest
    needs: generate-art
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Call OpenAI API to generate HTML
        run: |
          curl --fail --show-error https://api.openai.com/v1/chat/completions \
                -H "Authorization: Bearer $OPENAI_API_KEY" \
                -H "Content-Type: application/json" \
                -d @- > response.json <<EOF
          {
            "model": "gpt-4",
            "messages": [
              {
                "role": "system",
                "content": "You are a helpful assistant that writes clean HTML code. Only return valid HTML without any explanation."
              },
              {
                "role": "user",
                "content": "Write a full HTML document for the following: Give info about the rumored Lexus LFR speculations, like engine, transmission, price, etc. Include an <img src=\"image.png\" alt=\"AI-generated art\"> somewhere in the body. Add an internal <style> block in the <head> using the following design theme: Modern and minimalist, similar to Apple's theme. The CSS should include styling for layout and typography. Do not include JavaScript. Output only the HTML code."
              }
            ],
            "temperature": 0.2
          }
          EOF

      - name: Extract HTML from response
        run: |
          jq -r '.choices[0].message.content' response.json > index.html

      - name: Commit and push generated HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add index.html
          git commit -m "Auto-generate index.html using OpenAI API" || echo "No changes to commit"
          git push
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: generate-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
