name: Generate HTML

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Describe the type of HTML page to generate"
        required: true
        default: "Generate a very simple plaintext-style website that describes the rumored Lexus LFR."

jobs:
  generate-html:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Call OpenAI API to generate HTML
        run: |
          curl --fail --show-error https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {
                  "role": "system",
                  "content": "You are a helpful assistant that writes clean HTML code. Only return valid HTML without any explanation, markdown, or formatting."
                },
                {
                  "role": "user",
                  "content": "Write a full HTML document for the following: ${{ github.event.inputs.prompt }}  Do not include any CSS or JavaScript. Use only basic HTML tags like <html>, <head>, <body>, <h1>, <p>. Output only the HTML code"
                }
              ],
              "temperature": 0.2
            }' > response.json

      - name: Extract HTML from response
        run: |
          jq -r '.choices[0].message.content' response.json > index.html

      - name: Commit and push generated HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-generate index.html using OpenAI API" || echo "No changes to commit"
          git push
